apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: images
  labels:
    strimzi.io/cluster: modh-demo
spec:
  partitions: 1
  replicas: 1
  topicName: images
  config:
    retention.ms: 7200000